## Findings

This project consisted of exploratory analysis in the world of Pokemon. It mainly dealt with stats of individual pokemon and which type combinations were the most prevalent based on the generation (or game). While there were a lot of factors that the API did not consider, I found that there as at least one type of pokemon (i.e. fire or psychic in the generations I examined) that were “must-catches” in the game. Pokemon such are `Arcanine` in `Generation 1` or `Slaking` in `Generation 3` had high enough stats and a variety of powerful moves that made them necessary for any pokemon team. Most of the pokemon that were examined were legendaries or “pseudo-legendaries”, which essentially meant that they were strong enough to be on par with legendary pokemon. However, the one aspect of this `totalstats` variable that I found interesting was from the generations that were examined, every starter pokemon made the list of top 25 strongest. This meant that there wasn’t necessarily a “correct choice”, but rather was made solely on the player’s preference. Catch rate was another interesting factor, as certain powerful pokemon were pretty easy to catch compared to other, weaker pokemon. Evolutions were not taken into account, though it would be interesting to see which pokemon were easier to level up than others/take experience points into account. Spread was also very interesting, as `Water` types dominated in quantity but were lacking in quality (minus the legendary pokemon), where as `Psychic` types were lesser in quantity but had higher overall stats. I would have assumed `Dragon` types would be the least in number but the strongest in stats, but after looking into the spread, it was not the case.

## Future Expectations

The most difficult part of this project was definitely the functions. I learned quite quickly that pulling data the way I want and parsing through a URL in a function was quite difficult, and I could not completely pull all the information that I desired for this project. I wanted to take regions into account, and figure out a way to calculate encounter rate for each pokemon (where to find the strong ones for instance), but I couldn’t come up with a way to do so, even though there was some information pertaining to it. Figuring out what data I wanted to tell a story on was also quite tricky, as I could have taken many different avenues to hone in on one specific aspect. Given that there were multiple types of pokemon, especially with combinations, the idea of Psychic being the strongest is still pretty brash to say, as there are different combinations (say `Psychic/Fire`) that could actually lead to a much stronger and versatile typing. Stat boost items and other perks were also not considered, even though `Items` was also something I could have pulled from the API. All in all, I could have done more with the functions, though I did learn quite a bit about parsing through the URLs needed in an API to try to dive deeper into a project like this. In the future, I would very much like to expand my way of thinking in how different variables could interact with each other (essentially trying to grow my storytelling in data). I believe that this project was a nice introduction to how I could tie in my findings to an actual scenario (i.e. come up with certain pokemon teams in each generation and say this is this best team to go with), but as I close off this project and start on the next, I want to get better at telling a story. 

## Github Pages and Repo Links

- [github repo](https://github.com/suproman98/pokeAPI-Vignette.git)
- [github pages](https://suproman98.github.io/pokeAPI-Vignette/)
